<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.martinpaljak</groupId>
    <artifactId>gppro</artifactId>
    <version>25.07.08-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>GlobalPlatformPro</name>
    <description>Manage applets and keys on JavaCard-s like a pro</description>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.outputTimestamp>2025-07-08T05:29:20Z</project.build.outputTimestamp>
    </properties>

    <repositories>
        <repository>
            <id>javacard-pro</id>
            <url>https://mvn.javacard.pro/maven/</url>
        </repository>
        <repository>
            <id>javacard-pro-snapshots</id>
            <url>https://mvn.javacard.pro/maven/SNAPSHOTS/</url>
        </repository>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>

    <modules>
        <module>library</module>
        <module>pace</module>
        <module>tool</module>
    </modules>

    <build>
        <plugins>
            <!-- Compiler Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>21</release>
                </configuration>
            </plugin>

            <!-- SpotBugs Plugin (disabled) -->
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>4.8.3.0</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.martinpaljak</groupId>
                <artifactId>apdu4j-core</artifactId>
                <version>25.03.11</version>
            </dependency>
            <dependency>
                <groupId>com.github.martinpaljak</groupId>
                <artifactId>apdu4j-pcsc</artifactId>
                <version>25.03.11</version>
            </dependency>
            <dependency>
                <groupId>com.payneteasy</groupId>
                <artifactId>ber-tlv</artifactId>
                <version>1.0-11</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>

